import './globals.css'
import { Inter } from 'next/font/google'
import AuthNavbar from "../../components/AuthNavbar"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='antialiased'>
      <body className={inter.className}>
        <AuthNavbar />
        {children}
      </body>
    </html>
  )
}
