import '../globals.css';
import Center from '@/components/Center';
import UnAuthNavbar from '@/components/UnAuthNavbar';

export const metadata = {
    title: 'Feed Page',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <>
            <Center>
                <UnAuthNavbar />
                {children}
            </Center>
        </>
    );
}
